name: PPG
description: Measure HRV using the phone's camera.

version: 1.0.1+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  charts_flutter: ^0.11.0
  wakelock: ^0.1.4+1
  camera: 0.7.0+4
  scidart: ^0.0.2-dev.6
  numdart: ^1.0.0
  percent_indicator: "^2.1.7+2"
  iirjdart: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/logo_rounded.png"



flutter:
  uses-material-design: true
